import './home.css'

function Main(){
    return(
        <div className="main">
        <div className="main_container">    
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs acts act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs act"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="divs"></div>
            <div className="m_cont">
                <h1 className="main_title">A Digital Product Studio <br /> that will Work</h1>
                <div className="btn_wrap">
                    <button className="btn_item btn1">Our Works</button>
                    <button className="btn_item btn2">Contact Us</button>
                </div>
                </div>
            </div>
        </div>
    )
}

export default Main